name: Import Products from Multiple CSV Files

on:
  push:
    branches: [ main ]
    paths: 
      - 'product-data/**/*.csv'
  workflow_dispatch:
    inputs:
      folder_path:
        description: 'Folder path to process CSV files'
        required: true
        default: 'product-data'
      specific_file:
        description: 'Specific CSV file to process (optional)'
        required: false
        default: ''
      process_all:
        description: 'Process all CSV files in folder'
        type: boolean
        required: false
        default: false

jobs:
  detect-changed-files:
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changes.outputs.changed-files }}
      has-changes: ${{ steps.changes.outputs.has-changes }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2  # Need at least 2 commits to detect changes

    - name: Detect changed CSV files
      id: changes
      run: |
        echo "🔍 Detecting changed files..."
        
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "📝 Manual trigger detected"
          
          if [ "${{ github.event.inputs.process_all }}" = "true" ]; then
            echo "🗂️ Processing all CSV files"
            FOUND_FILES=$(find ${{ github.event.inputs.folder_path }} -name '*.csv' 2>/dev/null || echo "")
          elif [ -n "${{ github.event.inputs.specific_file }}" ]; then
            echo "📄 Processing specific file: ${{ github.event.inputs.specific_file }}"
            FOUND_FILES="${{ github.event.inputs.specific_file }}"
          else
            echo "🗂️ Processing all CSV files in folder"
            FOUND_FILES=$(find ${{ github.event.inputs.folder_path }} -name '*.csv' 2>/dev/null || echo "")
          fi
          
          if [ -n "$FOUND_FILES" ]; then
            echo "changed-files=$FOUND_FILES" >> $GITHUB_OUTPUT
            echo "has-changes=true" >> $GITHUB_OUTPUT
            echo "✅ Found files: $FOUND_FILES"
          else
            echo "has-changes=false" >> $GITHUB_OUTPUT
            echo "⚠️ No CSV files found"
          fi
          
        else
          echo "🔄 Push trigger detected"
          
          # For push events, detect changed files
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            # First push to branch
            echo "🆕 First push to branch - processing all CSV files"
            CHANGED_FILES=$(find product-data -name '*.csv' 2>/dev/null || echo "")
          else
            # Regular push - detect changed files
            echo "📋 Detecting changed files between commits"
            CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.csv$' | grep '^product-data/' || echo "")
          fi
          
          if [ -n "$CHANGED_FILES" ]; then
            echo "changed-files=$CHANGED_FILES" >> $GITHUB_OUTPUT
            echo "has-changes=true" >> $GITHUB_OUTPUT
            echo "✅ Changed CSV files detected: $CHANGED_FILES"
          else
            echo "has-changes=false" >> $GITHUB_OUTPUT
            echo "ℹ️ No CSV files changed"
          fi
        fi

  import-products:
    needs: detect-changed-files
    if: needs.detect-changed-files.outputs.has-changes == 'true'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        
    - name: Install compatible dependencies
      run: |
        pip install --upgrade pip
        pip install numpy==1.26.4
        pip install pandas==2.2.3
        pip install -r requirements.txt
        
    - name: Verify detected files
      run: |
        echo "🔍 Files to process: ${{ needs.detect-changed-files.outputs.changed-files }}"
        
        # Convert to array and check each file exists
        FILES="${{ needs.detect-changed-files.outputs.changed-files }}"
        for file in $FILES; do
          if [ -f "$file" ]; then
            echo "✅ Found: $file"
          else
            echo "❌ Missing: $file"
          fi
        done
        
    - name: Run import script
      env:
        SHOPIFY_SHOP_DOMAIN: ${{ secrets.SHOPIFY_SHOP_DOMAIN }}
        SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
        SHOPIFY_API_VERSION: ${{ secrets.SHOPIFY_API_VERSION }}
        CHANGED_FILES: ${{ needs.detect-changed-files.outputs.changed-files }}
      run: |
        echo "🚀 Starting import with files: $CHANGED_FILES"
        python main.py
      
    - name: Upload import results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: import-results-${{ github.run_number }}
        path: |
          logs/*.log
          product-data/**/*.csv
